server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /api/custody/ {
    proxy_pass http://custody:8001/;
  }

  location /api/settlement/ {
    proxy_pass http://settlement:8002/;
  }

  location /api/recon/ {
    proxy_pass http://recon:8003/;
  }

  location /api/audit/ {
    proxy_pass http://auditlog:8004/;
  }
}
